// TEST NET
export const TEST_NET_KOVAN = 42

export const SUPPORTED_CHAINS_TEST_NET = [TEST_NET_KOVAN, TEST_NET_RSK]

// MAIN NET
export const MAIN_NET_POLYGON = 137

export const SUPPORTED_CHAINS_MAIN_NET = [MAIN_NET_POLYGON]

export const ALL_CHAINS = [...SUPPORTED_CHAINS_TEST_NET, ...SUPPORTED_CHAINS_MAIN_NET]
